public with sharing class SoqlQueryExercises {
    public SoqlQueryExercises() {
        /**
         * 1.Write a method to insert an Account record. Also insert five related contacts to that same account.

            2.Write a SOQL query to fetch the contact records that were inserted in previous question. (Hint: Use the CreatedDate field to add filter)

            3.Write a query on Contact object and fetch the Account details. Use child to parent relationship query.

            4.Write a query on Account object and fetch the related contacts. Use the parent to child relationship query.
         * 
         */
    }
}
